/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Classes.AppUser;
import Classes.AplicationSystem;
import Classes.Servidor;
import Classes.Feed;
import Classes.RegistoInterface;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.*;
import java.net.InetAddress;
import java.net.Socket;
import java.rmi.registry.LocateRegistry;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author nicol
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    private AplicationSystem system;
    Servidor servidor = null;
    String SERVICE_NAME = "/RegistoRemoteServer";

    public PaginaInicial(AplicationSystem system) {
        this.system = system;
        servidor = new Servidor(system);
        servidor.start();
        initComponents();
        this.setLocationRelativeTo(null);

        PaginaInicial.setVisible(true);
        ListaAmigos.setVisible(false);
        AdicionarAmigos.setVisible(false);

        jLabel20.setText(system.getOnGoingUser().getNameUser());

        jTable4.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 28));
        jTable4.getTableHeader().setOpaque(true);
        jTable4.getTableHeader().setBackground(new Color(10, 100, 200));
        jTable4.getTableHeader().setForeground(Color.WHITE);

        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setBackground(new Color(10, 100, 200));
        jTable1.getTableHeader().setForeground(Color.WHITE);

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);

        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable2.getTableHeader().setOpaque(true);
        jTable2.getTableHeader().setBackground(new Color(10, 100, 200));
        jTable2.getTableHeader().setForeground(Color.WHITE);

        TableRowSorter<TableModel> sorter1 = new TableRowSorter<>(jTable2.getModel());
        jTable2.setRowSorter(sorter1);

        jTable3.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable3.getTableHeader().setOpaque(true);
        jTable3.getTableHeader().setBackground(new Color(10, 100, 200));
        jTable3.getTableHeader().setForeground(Color.WHITE);

        TableRowSorter<TableModel> sorter2 = new TableRowSorter<>(jTable3.getModel());
        jTable3.setRowSorter(sorter2);

        PreencherTabelaFeed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PaginaInicialPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ListaAmigosPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AdicionarAmigoPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PaginaInicial = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        ListaAmigos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AdicionarAmigos = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sharetty");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("jLabel20");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/people_50px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sharetty");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 50));

        PaginaInicialPanel.setBackground(new java.awt.Color(255, 255, 255));
        PaginaInicialPanel.setOpaque(false);
        PaginaInicialPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaginaInicialPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaginaInicialPanelMouseEntered(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/home_40px_Orange.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(29, 182, 239));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 136, 37));
        jLabel4.setText("Página Inicial");

        javax.swing.GroupLayout PaginaInicialPanelLayout = new javax.swing.GroupLayout(PaginaInicialPanel);
        PaginaInicialPanel.setLayout(PaginaInicialPanelLayout);
        PaginaInicialPanelLayout.setHorizontalGroup(
            PaginaInicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaginaInicialPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PaginaInicialPanelLayout.setVerticalGroup(
            PaginaInicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaginaInicialPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(PaginaInicialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 70));
        PaginaInicialPanel.getAccessibleContext().setAccessibleName("");

        ListaAmigosPanel.setBackground(new java.awt.Color(255, 255, 255));
        ListaAmigosPanel.setOpaque(false);
        ListaAmigosPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaAmigosPanelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/friends_45px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lista de Amigos");

        javax.swing.GroupLayout ListaAmigosPanelLayout = new javax.swing.GroupLayout(ListaAmigosPanel);
        ListaAmigosPanel.setLayout(ListaAmigosPanelLayout);
        ListaAmigosPanelLayout.setHorizontalGroup(
            ListaAmigosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAmigosPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ListaAmigosPanelLayout.setVerticalGroup(
            ListaAmigosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaAmigosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListaAmigosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(ListaAmigosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 270, 70));

        AdicionarAmigoPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdicionarAmigoPanel.setOpaque(false);
        AdicionarAmigoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdicionarAmigoPanelMouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/add_user_group_man_man_40px_white.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adicionar Amigos");

        javax.swing.GroupLayout AdicionarAmigoPanelLayout = new javax.swing.GroupLayout(AdicionarAmigoPanel);
        AdicionarAmigoPanel.setLayout(AdicionarAmigoPanelLayout);
        AdicionarAmigoPanelLayout.setHorizontalGroup(
            AdicionarAmigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionarAmigoPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        AdicionarAmigoPanelLayout.setVerticalGroup(
            AdicionarAmigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionarAmigoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionarAmigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(AdicionarAmigoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 270, 70));

        LogoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogoutPanel.setOpaque(false);
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/logout_rounded_left_60px_white.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sair");

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(28, 28, 28))
        );

        jPanel2.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 120, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/image (1).png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 920));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 920));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1290, 920));

        PaginaInicial.setBackground(new java.awt.Color(255, 255, 255));
        PaginaInicial.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 136, 37));
        jLabel15.setText("Feed");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/rss_40px.png"))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(226, 111));

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setMaximumSize(new java.awt.Dimension(224, 109));
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(255, 136, 37));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Share");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setRowHeight(100);
        jTable4.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable4.setShowHorizontalLines(false);
        jTable4.setShowVerticalLines(false);
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout PaginaInicialLayout = new javax.swing.GroupLayout(PaginaInicial);
        PaginaInicial.setLayout(PaginaInicialLayout);
        PaginaInicialLayout.setHorizontalGroup(
            PaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaginaInicialLayout.createSequentialGroup()
                .addGroup(PaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PaginaInicialLayout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(PaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PaginaInicialLayout.createSequentialGroup()
                            .addGap(428, 428, 428)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12))))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        PaginaInicialLayout.setVerticalGroup(
            PaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaginaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        ListaAmigos.setBackground(new java.awt.Color(255, 255, 255));
        ListaAmigos.setPreferredSize(new java.awt.Dimension(1290, 870));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 136, 37));
        jLabel13.setText("Amizades");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/handshake_40px.png"))); // NOI18N

        jScrollPane2.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Email", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 175, 100));
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout ListaAmigosLayout = new javax.swing.GroupLayout(ListaAmigos);
        ListaAmigos.setLayout(ListaAmigosLayout);
        ListaAmigosLayout.setHorizontalGroup(
            ListaAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAmigosLayout.createSequentialGroup()
                .addGroup(ListaAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaAmigosLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListaAmigosLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        ListaAmigosLayout.setVerticalGroup(
            ListaAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        AdicionarAmigos.setBackground(new java.awt.Color(255, 255, 255));
        AdicionarAmigos.setPreferredSize(new java.awt.Dimension(1290, 870));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 136, 37));
        jLabel16.setText("Procurar Amigos");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosd/Icons/add_40px.png"))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Email", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(255, 175, 100));
        jTable2.setShowVerticalLines(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Enviar Pedidos");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Pedidos Pendentes");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Email", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable3.setRowHeight(25);
        jTable3.setSelectionBackground(new java.awt.Color(255, 175, 100));
        jTable3.setShowVerticalLines(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jButton2.setBackground(new java.awt.Color(255, 136, 37));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Aceitar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Recusar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nome", "Email", "Curso", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 136, 37));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Procurar");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdicionarAmigosLayout = new javax.swing.GroupLayout(AdicionarAmigos);
        AdicionarAmigos.setLayout(AdicionarAmigosLayout);
        AdicionarAmigosLayout.setHorizontalGroup(
            AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionarAmigosLayout.createSequentialGroup()
                .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionarAmigosLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AdicionarAmigosLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))
                                .addGroup(AdicionarAmigosLayout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AdicionarAmigosLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        AdicionarAmigosLayout.setVerticalGroup(
            AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionarAmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addGap(10, 10, 10)
                .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(PaginaInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ListaAmigos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AdicionarAmigos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListaAmigos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdicionarAmigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ListaAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdicionarAmigos, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1290, 920));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botao Logout
    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        servidor.stopRunning();
        Login u = new Login(system);
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutPanelMouseClicked

    //Botao PaginaInicial
    private void PaginaInicialPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaginaInicialPanelMouseClicked
        jLabel4.setForeground(new Color(255, 136, 37));
        jLabel7.setForeground(new Color(255, 255, 255));
        jLabel8.setForeground(new Color(255, 255, 255));

        jLabel3.setIcon(new ImageIcon("./src/projetosd/Icons/home_40px_Orange.png"));
        jLabel5.setIcon(new ImageIcon("./src/projetosd/Icons/friends_45px.png"));
        jLabel6.setIcon(new ImageIcon("./src/projetosd/Icons/add_user_group_man_man_40px_white.png"));

        PreencherTabelaFeed();

        PaginaInicial.setVisible(true);
        ListaAmigos.setVisible(false);
        AdicionarAmigos.setVisible(false);
    }//GEN-LAST:event_PaginaInicialPanelMouseClicked

    //Botao Lista de Amigos
    private void ListaAmigosPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaAmigosPanelMouseClicked
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel7.setForeground(new Color(255, 136, 37));
        jLabel8.setForeground(new Color(255, 255, 255));

        jLabel3.setIcon(new ImageIcon("./src/projetosd/Icons/home_40px.png"));
        jLabel5.setIcon(new ImageIcon("./src/projetosd/Icons/friends_45px_Orange.png"));
        jLabel6.setIcon(new ImageIcon("./src/projetosd/Icons/add_user_group_man_man_40px_white.png"));

        try {

            RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

            system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 0, ""));

        } catch (Exception Exept) {
            System.out.println("Error: " + Exept);
        }

        PreencherTabelaAmigos();

        PaginaInicial.setVisible(false);
        ListaAmigos.setVisible(true);
        AdicionarAmigos.setVisible(false);
    }//GEN-LAST:event_ListaAmigosPanelMouseClicked

    //Botao Lista Utilizadores
    private void AdicionarAmigoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdicionarAmigoPanelMouseClicked
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel7.setForeground(new Color(255, 255, 255));
        jLabel8.setForeground(new Color(255, 136, 37));

        jLabel3.setIcon(new ImageIcon("./src/projetosd/Icons/home_40px.png"));
        jLabel5.setIcon(new ImageIcon("./src/projetosd/Icons/friends_45px.png"));
        jLabel6.setIcon(new ImageIcon("./src/projetosd/Icons/add_user_group_man_man_40px_Orange.png"));

        try {

            RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

            system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 0, ""));

        } catch (Exception Exept) {
            System.out.println("Error: " + Exept);
        }

        PreencherTabelaPedidos();
        PreencherTabelaUsers();

        PaginaInicial.setVisible(false);
        ListaAmigos.setVisible(false);
        AdicionarAmigos.setVisible(true);
    }//GEN-LAST:event_AdicionarAmigoPanelMouseClicked

    private void PaginaInicialPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaginaInicialPanelMouseEntered

    }//GEN-LAST:event_PaginaInicialPanelMouseEntered

    //Botao Share Enviar Estado
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String estado = jTextArea1.getText();
        String nome = system.getOnGoingUser().getNameUser();
        String estadoFormatado = estado.replaceAll(" ", "&nbsp;");

        String request = "EnviarEstado" + " " + nome + " " + estadoFormatado;
        int numero = 0;

        try {
            RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

            system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 0, ""));

        } catch (Exception Exept) {
            System.out.println("Error: " + Exept);
        }

        for (AppUser utilizador : system.getOnGoingUser().getFriendsUser()) {
            for (AppUser u : system.getEntireAppUsers().getAppUsers()) {
                if (u.getAdressUser().equals(utilizador.getAdressUser())) {
                    try {
                        Socket ligacao = new Socket(u.getIpUser(), u.getPortaUser());

                        BufferedReader entrada = new BufferedReader(new InputStreamReader(ligacao.getInputStream()));
                        PrintWriter saida = new PrintWriter(ligacao.getOutputStream(), true);

                        saida.println(request);

                        String msg = entrada.readLine();

                        if (!msg.equals("200")) {
                            JOptionPane.showMessageDialog(PaginaInicial, "Ocorreu um erro no envio da mensagem ao utilizador:" + utilizador.getNameUser());
                        } else if (msg.equals("200")) {
                            PreencherTabelaFeed();
                        }

                        saida.flush();
                        entrada.close();
                        saida.close();
                        ligacao.close();
                    } catch (Exception e) {
                        System.out.print(e);
                        numero++;
                    }
                }
            }
        }

        //Feed feed = new Feed(nome, estado);
        //system.getUtilizadorAtual().insereFeed(feed);
        PreencherTabelaFeed();

        jTextArea1.setText("");
        if (numero != 0) {
            JOptionPane.showMessageDialog(PaginaInicial, numero + " utilizadores não se encontram online e não receberam a mensagem");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    //Selecionar Linha Para enviar pedido
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int row = jTable3.getSelectedRow();
        String nome = jTable3.getModel().getValueAt(row, 0).toString();
        String email = jTable3.getModel().getValueAt(row, 1).toString();

        String request = "EnviarPedidoAmizade" + " " + system.getOnGoingUser().getAdressUser();

        if (JOptionPane.showConfirmDialog(null, "Deseja Enviar Pedido de Amizade a " + nome, "Confirm", JOptionPane.CANCEL_OPTION, JOptionPane.OK_CANCEL_OPTION) != 2) {
            for (AppUser utilizador : system.getEntireAppUsers().getAppUsers()) {
                if (utilizador.getAdressUser().equals(email)) {
                    try {
                        Socket ligacao = new Socket(utilizador.getIpUser(), utilizador.getPortaUser());

                        BufferedReader entrada = new BufferedReader(new InputStreamReader(ligacao.getInputStream()));
                        PrintWriter saida = new PrintWriter(ligacao.getOutputStream(), true);

                        saida.println(request);

                        String msg = entrada.readLine();

                        if (!msg.equals("201")) {
                            JOptionPane.showMessageDialog(AdicionarAmigos, "Ocorreu um erro no envio do pedido ao utilizador: " + utilizador.getNameUser());
                        } else {
                            JOptionPane.showMessageDialog(AdicionarAmigos, "Pedido de amizade ao utilizador: " + utilizador.getNameUser());
                        }

                        saida.flush();
                        entrada.close();
                        saida.close();
                        ligacao.close();
                    } catch (Exception e) {
                        System.out.print(e);
                        JOptionPane.showMessageDialog(AdicionarAmigos, "O utilizador" + utilizador.getNameUser() + "não se encontra online");
                    }

                    PreencherTabelaAmigos();
                    PreencherTabelaPedidos();
                    PreencherTabelaUsers();
                }
            }
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    }//GEN-LAST:event_jTable2MouseClicked

    //Aceitar Pedido Amizade
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (jTable2.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(AdicionarAmigos, "Selecione um utilizador para adicionar");
        } else {
            int row = jTable2.getSelectedRow();
            String nome = jTable2.getModel().getValueAt(row, 0).toString();
            String email = jTable2.getModel().getValueAt(row, 1).toString();

            String request = "ResponderPedidoAmizade" + " " + system.getOnGoingUser().getAdressUser() + " YES";

            for (AppUser u : system.getEntireAppUsers().getAppUsers()) {
                if (u.getAdressUser().equals(email)) {
                    try {
                        Socket ligacao = new Socket(u.getIpUser(), u.getPortaUser());

                        BufferedReader entrada = new BufferedReader(new InputStreamReader(ligacao.getInputStream()));
                        PrintWriter saida = new PrintWriter(ligacao.getOutputStream(), true);

                        saida.println(request);

                        String msg = entrada.readLine();

                        if (!msg.equals("200")) {
                            JOptionPane.showMessageDialog(AdicionarAmigos, "Ocorreu um erro no envio da mensagem ao utilizador: " + u.getNameUser());
                        }

                        saida.flush();
                        entrada.close();
                        saida.close();
                        ligacao.close();

                    } catch (Exception e) {
                        System.out.print(e);
                        JOptionPane.showMessageDialog(AdicionarAmigos, "O utilizador " + u.getNameUser() + " não se encontra online");
                    }

                    system.getOnGoingUser().removeRequest(u.getAdressUser());
                    system.getOnGoingUser().insereFriend(u);

                    PreencherTabelaAmigos();
                    PreencherTabelaPedidos();
                    PreencherTabelaUsers();
                }
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    //Recusar pedido amziade
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (jTable2.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(AdicionarAmigos, "Selecione um utilizador para adicionar");
        } else {
            int row = jTable2.getSelectedRow();
            String nome = jTable2.getModel().getValueAt(row, 0).toString();
            String email = jTable2.getModel().getValueAt(row, 1).toString();

            String request = "ResponderPedidoAmizade" + " " + system.getOnGoingUser().getAdressUser() + " NO";

            for (AppUser u : system.getEntireAppUsers().getAppUsers()) {
                if (u.getAdressUser().equals(email)) {
                    try {
                        Socket ligacao = new Socket(u.getIpUser(), u.getPortaUser());

                        BufferedReader entrada = new BufferedReader(new InputStreamReader(ligacao.getInputStream()));
                        PrintWriter saida = new PrintWriter(ligacao.getOutputStream(), true);

                        saida.println(request);

                        String msg = entrada.readLine();

                        if (!msg.equals("200")) {
                            JOptionPane.showMessageDialog(AdicionarAmigos, "Ocorreu um erro no envio da mensagem ao utilizador:" + u.getNameUser());
                        }

                        saida.flush();
                        entrada.close();
                        saida.close();
                        ligacao.close();

                    } catch (Exception e) {
                        System.out.print(e);
                        JOptionPane.showMessageDialog(AdicionarAmigos, "O utilizador " + u.getNameUser() + "não se encontra online");
                    }

                    system.getOnGoingUser().removeRequest(u.getAdressUser());

                    PreencherTabelaAmigos();
                    PreencherTabelaPedidos();
                    PreencherTabelaUsers();
                }
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String value = jComboBox1.getSelectedItem().toString();

        if (value.equals("Todos")) {
            try {

                    RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

                    system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 0, ""));

                } catch (Exception Exept) {
                    System.out.println("Error: " + Exept);
                }
        } else if (value.equals("Nome")) {
            if (jTextField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Introduza o Nome");
                jTextField1.requestFocus();
                return;
            } else {
                try {

                    RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

                    system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 1, jTextField1.getText()));

                } catch (Exception Exept) {
                    System.out.println("Error: " + Exept);
                }
            }
        } else if (value.equals("Email")) {
            if (jTextField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Introduza o Email");
                jTextField1.requestFocus();
                return;
            } else {
                try {

                    RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

                    system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 2, jTextField1.getText()));

                } catch (Exception Exept) {
                    System.out.println("Error: " + Exept);
                }
            }
        } else if (value.equals("Curso")) {
            if (jTextField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Introduza o Curso");
                jTextField1.requestFocus();
                return;
            } else {
                try {

                    RegistoInterface regInt = (RegistoInterface) LocateRegistry.getRegistry(InetAddress.getByName("DESKTOP-BJABO8J").getHostAddress()).lookup(SERVICE_NAME);

                    system.getEntireAppUsers().setAppUsers(regInt.getUsers(system.getOnGoingUser(), 3, jTextField1.getText()));

                } catch (Exception Exept) {
                    System.out.println("Error: " + Exept);
                }

            }
        }

        PreencherTabelaUsers();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PreencherTabelaFeed() {
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTable4.getModel();
        tabelaModelo.setNumRows(0);

        for (Feed feed : system.getOnGoingUser().getFeed()) {
            tabelaModelo.addRow(new Object[]{feed.getNomeUser(), feed.getMsgUser()});
        }
    }

    private void PreencherTabelaAmigos() {
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTable1.getModel();
        tabelaModelo.setNumRows(0);

        for (AppUser utilizador : system.getOnGoingUser().getFriendsUser()) {
            tabelaModelo.addRow(new Object[]{utilizador.getNameUser(), utilizador.getAdressUser(), utilizador.getCursoUMinho()});
        }
    }

    private void PreencherTabelaPedidos() {
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTable2.getModel();
        tabelaModelo.setNumRows(0);

        for (AppUser utilizador : system.getOnGoingUser().getRequestsOnHold()) {
            tabelaModelo.addRow(new Object[]{utilizador.getNameUser(), utilizador.getAdressUser(), utilizador.getCursoUMinho()});
        }
    }

    private void PreencherTabelaUsers() {
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTable3.getModel();
        tabelaModelo.setRowCount(0);
        ArrayList<AppUser> amigos = system.getOnGoingUser().getFriendsUser();
        boolean existe = false;

        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (AppUser utilizador : system.getEntireAppUsers().getAppUsers()) {
            existe = false;
            if (!(system.getOnGoingUser().getAdressUser().equals(utilizador.getAdressUser()))) {
                if (amigos.isEmpty()) {
                    tabelaModelo.addRow(new Object[]{utilizador.getNameUser(), utilizador.getAdressUser(), utilizador.getCursoUMinho()});
                } else {
                    for (AppUser user : amigos) {
                        if (user.getAdressUser().equals(utilizador.getAdressUser())) {
                            existe = true;
                        }
                    }
                    if(existe == false){
                        tabelaModelo.addRow(new Object[]{utilizador.getNameUser(), utilizador.getAdressUser(), utilizador.getCursoUMinho()});
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdicionarAmigoPanel;
    private javax.swing.JPanel AdicionarAmigos;
    private javax.swing.JPanel ListaAmigos;
    private javax.swing.JPanel ListaAmigosPanel;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel PaginaInicial;
    private javax.swing.JPanel PaginaInicialPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
